name: Deploy to Cloudflare Pages

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: installing node
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 20
      - name: installing pnpm
        uses: pnpm/action-setup@v4.0.0
        with:
          version: 9.3.0
          run_install: true

      - name: linter
        run: pnpm run lint
      - name: check
        run: pnpm run check

      - name: build
        run: pnpm run build

      - name: Publish to Cloudflare Workers
        run: npx wrangler publish
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}